In [2]:
import pandas as pd

df = pd.read_excel("cpv2020_b_bc_07_educacion copy.xlsx", sheet_name=4, header=5)

In [3]:
df.columns

Index(['Entidad federativa', 'Municipio', 'Sexo',
       'Grupos quinquenales de edad', 'Población de 15 años y más',
       'Condición de alfabetismo', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='str')

In [4]:
df["Municipio"]

0              NaN
1              NaN
2            Total
3            Total
4            Total
          ...
333    004 Tijuana
334    004 Tijuana
335    004 Tijuana
336    004 Tijuana
337    004 Tijuana
Name: Municipio, Length: 338, dtype: str

In [5]:
len(df["Municipio"])

338

In [6]:
set(df["Municipio"])

{'001 Ensenada',
 '002 Mexicali',
 '003 Tecate',
 '004 Tijuana',
 '005 Playas de Rosarito',
 '006 San Quintín',
 'Total',
 nan}

In [7]:
set(df["Sexo"])

{'Hombres', 'Mujeres', 'Total', nan}

In [8]:
df[["Municipio", "Sexo"]]

       Municipio     Sexo
0            NaN      NaN
1            NaN      NaN
2          Total    Total
3          Total    Total
4          Total    Total
..           ...      ...
333  004 Tijuana  Mujeres
334  004 Tijuana  Mujeres
335  004 Tijuana  Mujeres
336  004 Tijuana  Mujeres
337  004 Tijuana  Mujeres

[338 rows x 2 columns]

In [9]:
df[["Municipio", "Condición de alfabetismo"]]

       Municipio Condición de alfabetismo
0            NaN                 Alfabeta
1            NaN                      NaN
2          Total                  2817601
3          Total                   312343
4          Total                   335947
..           ...                      ...
333  004 Tijuana                    21033
334  004 Tijuana                    14120
335  004 Tijuana                     8569
336  004 Tijuana                     5377
337  004 Tijuana                     4044

[338 rows x 2 columns]

In [10]:
df["Condición de alfabetismo"].describe()

count      337
unique     336
top       1394
freq         2
Name: Condición de alfabetismo, dtype: int64

In [11]:
df.iloc[51]

Entidad federativa             02 Baja California
Municipio                            001 Ensenada
Sexo                                        Total
Grupos quinquenales de edad            15-19 años
Población de 15 años y más                36228.0
Condición de alfabetismo                    35866
Unnamed: 6                                    227
Unnamed: 7                                    135
Name: 51, dtype: object

In [12]:
df.head()

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,Alfabeta,Analfabeta,No especificado
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02 Baja California,Total,Total,Total,2882498.0,2817601,52496,12401
3,02 Baja California,Total,Total,15-19 años,315639.0,312343,1595,1701
4,02 Baja California,Total,Total,20-24 años,340359.0,335947,2046,2366

In [14]:
df[df["Sexo"]=="Mujeres"]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
34,02 Baja California,Total,Mujeres,Total,1432330.0,1398826,28441,5063
35,02 Baja California,Total,Mujeres,15-19 años,154341.0,152806,639,896
36,02 Baja California,Total,Mujeres,20-24 años,166909.0,164928,821,1160
37,02 Baja California,Total,Mujeres,25-29 años,161994.0,160447,948,599
38,02 Baja California,Total,Mujeres,30-34 años,150225.0,148504,1161,560
...,...,...,...,...,...,...,...,...
333,02 Baja California,004 Tijuana,Mujeres,65-69 años,22397.0,21033,1323,41
334,02 Baja California,004 Tijuana,Mujeres,70-74 años,15310.0,14120,1173,17
335,02 Baja California,004 Tijuana,Mujeres,75-79 años,9623.0,8569,1043,11
336,02 Baja California,004 Tijuana,Mujeres,80-84 años,6176.0,5377,788,11
337,02 Baja California,004 Tijuana,Mujeres,85 años y más,4913.0,4044,858,11

In [26]:
#El municipio es mexicali Y El sexo es mujeres
df[(df["Municipio"]=="002 Mexicali") & (df["Sexo"]=="Mujeres") ]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
130,02 Baja California,002 Mexicali,Mujeres,Total,404632.0,396570,6642,1420
131,02 Baja California,002 Mexicali,Mujeres,15-19 años,42890.0,42452,156,282
132,02 Baja California,002 Mexicali,Mujeres,20-24 años,44763.0,44274,172,317
133,02 Baja California,002 Mexicali,Mujeres,25-29 años,42502.0,42156,187,159
134,02 Baja California,002 Mexicali,Mujeres,30-34 años,40318.0,39969,212,137
135,02 Baja California,002 Mexicali,Mujeres,35-39 años,37920.0,37525,265,130
136,02 Baja California,002 Mexicali,Mujeres,40-44 años,37053.0,36562,379,112
137,02 Baja California,002 Mexicali,Mujeres,45-49 años,36253.0,35788,375,90
138,02 Baja California,002 Mexicali,Mujeres,50-54 años,31505.0,30914,517,74
139,02 Baja California,002 Mexicali,Mujeres,55-59 años,25526.0,24950,539,37
140,02 Baja California,002 Mexicali,Mujeres,60-64 años,22055.0,21374,655,26
141,02 Baja California,002 Mexicali,Mujeres,65-69 años,16032.0,15296,721,15
142,02 Baja California,002 Mexicali,Mujeres,70-74 años,11495.0,10810,673,12
143,02 Baja California,002 Mexicali,Mujeres,75-79 años,7435.0,6772,652,11
144,02 Baja California,002 Mexicali,Mujeres,80-84 años,4977.0,4429,542,6
145,02 Baja California,002 Mexicali,Mujeres,85 años y más,3908.0,3299,597,12

In [25]:
#El municipio es mexicali o El sexo es mujeres
df[(df["Municipio"]=="002 Mexicali") | (df["Sexo"]=="Mujeres") ]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
34,02 Baja California,Total,Mujeres,Total,1432330.0,1398826,28441,5063
35,02 Baja California,Total,Mujeres,15-19 años,154341.0,152806,639,896
36,02 Baja California,Total,Mujeres,20-24 años,166909.0,164928,821,1160
37,02 Baja California,Total,Mujeres,25-29 años,161994.0,160447,948,599
38,02 Baja California,Total,Mujeres,30-34 años,150225.0,148504,1161,560
...,...,...,...,...,...,...,...,...
333,02 Baja California,004 Tijuana,Mujeres,65-69 años,22397.0,21033,1323,41
334,02 Baja California,004 Tijuana,Mujeres,70-74 años,15310.0,14120,1173,17
335,02 Baja California,004 Tijuana,Mujeres,75-79 años,9623.0,8569,1043,11
336,02 Baja California,004 Tijuana,Mujeres,80-84 años,6176.0,5377,788,11
337,02 Baja California,004 Tijuana,Mujeres,85 años y más,4913.0,4044,858,11

In [30]:
df[df["Población de 15 años y más"]> 152806]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
2,02 Baja California,Total,Total,Total,2882498.0,2817601,52496,12401
3,02 Baja California,Total,Total,15-19 años,315639.0,312343,1595,1701
4,02 Baja California,Total,Total,20-24 años,340359.0,335947,2046,2366
5,02 Baja California,Total,Total,25-29 años,328244.0,324463,2217,1564
6,02 Baja California,Total,Total,30-34 años,302389.0,298211,2659,1519
7,02 Baja California,Total,Total,35-39 años,292069.0,287375,3278,1416
8,02 Baja California,Total,Total,40-44 años,273611.0,268415,3941,1255
9,02 Baja California,Total,Total,45-49 años,260844.0,256055,3889,900
10,02 Baja California,Total,Total,50-54 años,221388.0,216373,4420,595
11,02 Baja California,Total,Total,55-59 años,168653.0,163703,4558,392
18,02 Baja California,Total,Hombres,Total,1450168.0,1418775,24055,7338
19,02 Baja California,Total,Hombres,15-19 años,161298.0,159537,956,805
20,02 Baja California,Total,Hombres,20-24 años,173450.0,171019,1225,1206
21,02 Baja California,Total,Hombres,25-29 años,166250.0,164016,1269,965
34,02 Baja California,Total,Mujeres,Total,1432330.0,1398826,28441,5063
35,02 Baja California,Total,Mujeres,15-19 años,154341.0,152806,639,896
36,02 Baja California,Total,Mujeres,20-24 años,166909.0,164928,821,1160
37,02 Baja California,Total,Mujeres,25-29 años,161994.0,160447,948,599
50,02 Baja California,001 Ensenada,Total,Total,339720.0,331063,7752,905
66,02 Baja California,001 Ensenada,Hombres,Total,168532.0,164420,3605,507
82,02 Baja California,001 Ensenada,Mujeres,Total,171188.0,166643,4147,398
98,02 Baja California,002 Mexicali,Total,Total,814668.0,798457,13134,3077
114,02 Baja California,002 Mexicali,Hombres,Total,410036.0,401887,6492,1657
130,02 Baja California,002 Mexicali,Mujeres,Total,404632.0,396570,6642,1420
290,02 Baja California,004 Tijuana,Total,Total,1467282.0,1439256,21469,6557
291,02 Baja California,004 Tijuana,Total,15-19 años,160775.0,159043,771,961
292,02 Baja California,004 Tijuana,Total,20-24 años,176731.0,174444,909,1378
293,02 Baja California,004 Tijuana,Total,25-29 años,174408.0,172685,865,858
294,02 Baja California,004 Tijuana,Total,30-34 años,158114.0,156265,1027,822
295,02 Baja California,004 Tijuana,Total,35-39 años,155043.0,153127,1205,711
306,02 Baja California,004 Tijuana,Hombres,Total,736875.0,723500,9601,3774
322,02 Baja California,004 Tijuana,Mujeres,Total,730407.0,715756,11868,2783

In [34]:
df[df["Municipio"].str.startswith("T")]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
2,02 Baja California,Total,Total,Total,2882498.0,2817601,52496,12401
3,02 Baja California,Total,Total,15-19 años,315639.0,312343,1595,1701
4,02 Baja California,Total,Total,20-24 años,340359.0,335947,2046,2366
5,02 Baja California,Total,Total,25-29 años,328244.0,324463,2217,1564
6,02 Baja California,Total,Total,30-34 años,302389.0,298211,2659,1519
7,02 Baja California,Total,Total,35-39 años,292069.0,287375,3278,1416
8,02 Baja California,Total,Total,40-44 años,273611.0,268415,3941,1255
9,02 Baja California,Total,Total,45-49 años,260844.0,256055,3889,900
10,02 Baja California,Total,Total,50-54 años,221388.0,216373,4420,595
11,02 Baja California,Total,Total,55-59 años,168653.0,163703,4558,392
12,02 Baja California,Total,Total,60-64 años,134022.0,128833,4901,288
13,02 Baja California,Total,Total,65-69 años,94704.0,89676,4857,171
14,02 Baja California,Total,Total,70-74 años,65425.0,60905,4420,100
15,02 Baja California,Total,Total,75-79 años,40874.0,37005,3818,51
16,02 Baja California,Total,Total,80-84 años,25204.0,22283,2870,51
17,02 Baja California,Total,Total,85 años y más,19073.0,16014,3027,32
18,02 Baja California,Total,Hombres,Total,1450168.0,1418775,24055,7338
19,02 Baja California,Total,Hombres,15-19 años,161298.0,159537,956,805
20,02 Baja California,Total,Hombres,20-24 años,173450.0,171019,1225,1206
21,02 Baja California,Total,Hombres,25-29 años,166250.0,164016,1269,965
22,02 Baja California,Total,Hombres,30-34 años,152164.0,149707,1498,959
23,02 Baja California,Total,Hombres,35-39 años,148169.0,145524,1710,935
24,02 Baja California,Total,Hombres,40-44 años,138332.0,135470,2023,839
25,02 Baja California,Total,Hombres,45-49 años,134187.0,131653,1965,569
26,02 Baja California,Total,Hombres,50-54 años,112789.0,110404,2001,384
27,02 Baja California,Total,Hombres,55-59 años,84778.0,82537,1982,259
28,02 Baja California,Total,Hombres,60-64 años,65287.0,63072,2021,194
29,02 Baja California,Total,Hombres,65-69 años,44982.0,43014,1863,105
30,02 Baja California,Total,Hombres,70-74 años,30812.0,28922,1835,55
31,02 Baja California,Total,Hombres,75-79 años,18833.0,17287,1518,28
32,02 Baja California,Total,Hombres,80-84 años,11060.0,9930,1103,27
33,02 Baja California,Total,Hombres,85 años y más,7777.0,6683,1086,8
34,02 Baja California,Total,Mujeres,Total,1432330.0,1398826,28441,5063
35,02 Baja California,Total,Mujeres,15-19 años,154341.0,152806,639,896
36,02 Baja California,Total,Mujeres,20-24 años,166909.0,164928,821,1160
37,02 Baja California,Total,Mujeres,25-29 años,161994.0,160447,948,599
38,02 Baja California,Total,Mujeres,30-34 años,150225.0,148504,1161,560
39,02 Baja California,Total,Mujeres,35-39 años,143900.0,141851,1568,481
40,02 Baja California,Total,Mujeres,40-44 años,135279.0,132945,1918,416
41,02 Baja California,Total,Mujeres,45-49 años,126657.0,124402,1924,331
42,02 Baja California,Total,Mujeres,50-54 años,108599.0,105969,2419,211
43,02 Baja California,Total,Mujeres,55-59 años,83875.0,81166,2576,133
44,02 Baja California,Total,Mujeres,60-64 años,68735.0,65761,2880,94
45,02 Baja California,Total,Mujeres,65-69 años,49722.0,46662,2994,66
46,02 Baja California,Total,Mujeres,70-74 años,34613.0,31983,2585,45
47,02 Baja California,Total,Mujeres,75-79 años,22041.0,19718,2300,23
48,02 Baja California,Total,Mujeres,80-84 años,14144.0,12353,1767,24
49,02 Baja California,Total,Mujeres,85 años y más,11296.0,9331,1941,24

In [35]:
df[df["Municipio"].str.endswith("i")]

,Entidad federativa,Municipio,Sexo,Grupos quinquenales de edad,Población de 15 años y más,Condición de alfabetismo,Unnamed: 6,Unnamed: 7
98,02 Baja California,002 Mexicali,Total,Total,814668.0,798457,13134,3077
99,02 Baja California,002 Mexicali,Total,15-19 años,87742.0,86888,362,492
100,02 Baja California,002 Mexicali,Total,20-24 años,91917.0,90859,434,624
101,02 Baja California,002 Mexicali,Total,25-29 años,86787.0,85916,486,385
102,02 Baja California,002 Mexicali,Total,30-34 años,82139.0,81225,563,351
103,02 Baja California,002 Mexicali,Total,35-39 años,78703.0,77718,667,318
104,02 Baja California,002 Mexicali,Total,40-44 años,75478.0,74295,899,284
105,02 Baja California,002 Mexicali,Total,45-49 años,74330.0,73263,857,210
106,02 Baja California,002 Mexicali,Total,50-54 años,63688.0,62527,1011,150
107,02 Baja California,002 Mexicali,Total,55-59 años,50950.0,49743,1118,89
108,02 Baja California,002 Mexicali,Total,60-64 años,42347.0,41047,1228,72
109,02 Baja California,002 Mexicali,Total,65-69 años,30491.0,29175,1279,37
110,02 Baja California,002 Mexicali,Total,70-74 años,21202.0,19996,1185,21
111,02 Baja California,002 Mexicali,Total,75-79 años,13640.0,12490,1136,14
112,02 Baja California,002 Mexicali,Total,80-84 años,8703.0,7738,949,16
113,02 Baja California,002 Mexicali,Total,85 años y más,6551.0,5577,960,14
114,02 Baja California,002 Mexicali,Hombres,Total,410036.0,401887,6492,1657
115,02 Baja California,002 Mexicali,Hombres,15-19 años,44852.0,44436,206,210
116,02 Baja California,002 Mexicali,Hombres,20-24 años,47154.0,46585,262,307
117,02 Baja California,002 Mexicali,Hombres,25-29 años,44285.0,43760,299,226
118,02 Baja California,002 Mexicali,Hombres,30-34 años,41821.0,41256,351,214
119,02 Baja California,002 Mexicali,Hombres,35-39 años,40783.0,40193,402,188
120,02 Baja California,002 Mexicali,Hombres,40-44 años,38425.0,37733,520,172
121,02 Baja California,002 Mexicali,Hombres,45-49 años,38077.0,37475,482,120
122,02 Baja California,002 Mexicali,Hombres,50-54 años,32183.0,31613,494,76
123,02 Baja California,002 Mexicali,Hombres,55-59 años,25424.0,24793,579,52
124,02 Baja California,002 Mexicali,Hombres,60-64 años,20292.0,19673,573,46
125,02 Baja California,002 Mexicali,Hombres,65-69 años,14459.0,13879,558,22
126,02 Baja California,002 Mexicali,Hombres,70-74 años,9707.0,9186,512,9
127,02 Baja California,002 Mexicali,Hombres,75-79 años,6205.0,5718,484,3
128,02 Baja California,002 Mexicali,Hombres,80-84 años,3726.0,3309,407,10
129,02 Baja California,002 Mexicali,Hombres,85 años y más,2643.0,2278,363,2
130,02 Baja California,002 Mexicali,Mujeres,Total,404632.0,396570,6642,1420
131,02 Baja California,002 Mexicali,Mujeres,15-19 años,42890.0,42452,156,282
132,02 Baja California,002 Mexicali,Mujeres,20-24 años,44763.0,44274,172,317
133,02 Baja California,002 Mexicali,Mujeres,25-29 años,42502.0,42156,187,159
134,02 Baja California,002 Mexicali,Mujeres,30-34 años,40318.0,39969,212,137
135,02 Baja California,002 Mexicali,Mujeres,35-39 años,37920.0,37525,265,130
136,02 Baja California,002 Mexicali,Mujeres,40-44 años,37053.0,36562,379,112
137,02 Baja California,002 Mexicali,Mujeres,45-49 años,36253.0,35788,375,90
138,02 Baja California,002 Mexicali,Mujeres,50-54 años,31505.0,30914,517,74
139,02 Baja California,002 Mexicali,Mujeres,55-59 años,25526.0,24950,539,37
140,02 Baja California,002 Mexicali,Mujeres,60-64 años,22055.0,21374,655,26
141,02 Baja California,002 Mexicali,Mujeres,65-69 años,16032.0,15296,721,15
142,02 Baja California,002 Mexicali,Mujeres,70-74 años,11495.0,10810,673,12
143,02 Baja California,002 Mexicali,Mujeres,75-79 años,7435.0,6772,652,11
144,02 Baja California,002 Mexicali,Mujeres,80-84 años,4977.0,4429,542,6
145,02 Baja California,002 Mexicali,Mujeres,85 años y más,3908.0,3299,597,12